### PR TITLE
Updating the main() function

### PR DESCRIPTION
**Pull request by myid13221**
Hello Mate;
This request I am making to change your code for the repository here. I don't think it is correct and it would compile as it seriously lacks with a main function().
Thanks
And Regards.

### CODE REVIEW

**Comment by Ankit-2312** [comment]
Ya, I forgot to add. But, have you run the code on your machine though. Prefer C++.

**Comment by Ankit-2312** [comment]
Please Reply.

**Comment by myid13221** [comment]
Ya, I do did it.

**Comment by Ankit-2312** [comment]
Then, shall I merge it. Are you sure, because ots my college project.

**Comment by Ankit-2312** [comment]
*its

**Comment by myid13221** [comment]
Yes, you can, if , you feel so.
Thanks.

**Comment by Ankit-2312** [comment]
Okay, thank you

**Comment by Ankit-2312** [comment]
Merged successfully.

**Comment by myid13221** [comment]
Thanks

**Pull request merged**
